In [1]:
import pandas as pd
import numpy as np

In [4]:
madmax = pd.read_csv('../data/savant/scherzer_2015_to_2019.csv')

In [5]:
madmax

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment
0,FF,2019-09-24,92.7,-3.3274,5.2774,Max Scherzer,656514,453286,field_out,hit_into_play,...,2,4,4,2,4,2,4,2,Infield shift,Standard
1,CH,2019-09-24,84.4,-3.2967,5.2518,Max Scherzer,664068,453286,single,hit_into_play_no_out,...,2,4,4,2,4,2,4,2,Standard,Standard
2,FF,2019-09-24,97.4,-3.1352,5.3625,Max Scherzer,664068,453286,NaN,foul,...,2,4,4,2,4,2,4,2,Standard,Standard
3,SL,2019-09-24,84.8,-3.4005,5.0587,Max Scherzer,664068,453286,NaN,ball,...,2,4,4,2,4,2,4,2,Standard,Standard
4,CU,2019-09-24,79.1,-3.2917,5.3838,Max Scherzer,664068,453286,NaN,foul,...,2,4,4,2,4,2,4,2,Standard,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16291,FF,2015-04-06,94.7,-3.7692,5.5081,Max Scherzer,434158,453286,NaN,ball,...,0,0,0,0,0,0,0,0,Strategic,Standard
16292,CH,2015-04-06,87.2,-3.6916,5.7893,Max Scherzer,434158,453286,NaN,ball,...,0,0,0,0,0,0,0,0,Strategic,Standard
16293,FF,2015-04-06,95.6,-3.7339,5.5188,Max Scherzer,434158,453286,NaN,ball,...,0,0,0,0,0,0,0,0,Strategic,Standard
16294,FF,2015-04-06,94.2,-3.7084,5.8286,Max Scherzer,434158,453286,NaN,foul,...,0,0,0,0,0,0,0,0,Strategic,Standard
16295,FF,2015-04-06,91.2,-3.7174,5.7151,Max Scherzer,434158,453286,NaN,called_strike,...,0,0,0,0,0,0,0,0,Strategic,Standard

## Data Cleaning

In [6]:
new_cols = []

for c in madmax.columns:
    c = c.lower()
    c = c.replace(' ', '_')
    c = c.replace('(', '')
    c = c.replace(')', '')
    c = c.replace('_°', '')
    new_cols.append(c)
    
madmax.columns = new_cols

In [7]:
keep_cols = ['pitch_type', 'game_date', 'batter', 'release_speed', 'events', 'description', 'zone', 'des', 'stand',
            'home_team', 'away_team', 'type', 'balls', 'strikes', 'on_3b', 'on_2b', 'on_1b', 'outs_when_up',
            'inning', 'inning_topbot', 'sv_id', 'release_spin_rate', 'pitch_number', 'pitch_name', 'bat_score', 
             'fld_score', 'if_fielding_alignment', 'of_fielding_alignment']

madmax = madmax[keep_cols]

In [8]:
kill_cols = ['events']
kill_cols.append('description')
kill_cols.append('des')
madmax['nats_home1_away0'] = madmax.home_team.apply(lambda h: 1 if h == 'WSH' else 0)
kill_cols.append('away_team')
kill_cols.append('type')
kill_cols.append('balls')
kill_cols.append('strikes')
madmax['balls_strikes'] = madmax.balls.astype(str) + '_' + madmax.strikes.astype(str)
madmax.on_3b = madmax.on_3b.fillna(value=0)
madmax.on_3b = madmax.on_3b.apply(lambda r3: 0 if r3 == 0 else 1)
madmax.on_2b = madmax.on_2b.fillna(value=0)
madmax.on_2b
madmax.on_2b = madmax.on_2b.apply(lambda r2: 0 if r2 == 0 else 1)
madmax.on_2b.value_counts()
madmax.on_1b = madmax.on_1b.fillna(value=0)
madmax.on_1b
madmax.on_1b = madmax.on_1b.apply(lambda r1: 0 if r1 == 0 else 1)
madmax.on_1b.value_counts()
madmax['all_runners'] = 'fb:' + madmax.on_1b.iloc[:].astype(str) + '_' + \
                            'sb:' + madmax.on_2b.iloc[:].astype(str) + '_' +\
                            'tb:' + madmax.on_3b.iloc[:].astype(str)
kill_cols.append('inning_topbot')
kill_cols.append('pitch_name')
madmax = madmax.rename(columns={'bat_score': 'opp_score'})
madmax = madmax.rename(columns={'fld_score': 'nats_score'})
madmax = madmax.drop(columns=kill_cols)

/Users/algrhythm/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/algrhythm/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/algrhythm/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
/Users/algrhythm/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [9]:
madmax

,pitch_type,game_date,batter,release_speed,zone,stand,home_team,on_3b,on_2b,on_1b,...,sv_id,release_spin_rate,pitch_number,opp_score,nats_score,if_fielding_alignment,of_fielding_alignment,nats_home1_away0,balls_strikes,all_runners
0,FF,2019-09-24,656514,92.7,6.0,L,WSH,0,0,1,...,190925_005920,2299.0,1,4,2,Infield shift,Standard,1,0_0,fb:1_sb:0_tb:0
1,CH,2019-09-24,664068,84.4,9.0,R,WSH,0,0,0,...,190925_005823,1494.0,5,4,2,Standard,Standard,1,1_2,fb:0_sb:0_tb:0
2,FF,2019-09-24,664068,97.4,8.0,R,WSH,0,0,0,...,190925_005750,2465.0,4,4,2,Standard,Standard,1,1_2,fb:0_sb:0_tb:0
3,SL,2019-09-24,664068,84.8,14.0,R,WSH,0,0,0,...,190925_005726,2295.0,3,4,2,Standard,Standard,1,0_2,fb:0_sb:0_tb:0
4,CU,2019-09-24,664068,79.1,4.0,R,WSH,0,0,0,...,190925_005705,2818.0,2,4,2,Standard,Standard,1,0_1,fb:0_sb:0_tb:0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16291,FF,2015-04-06,434158,94.7,11.0,L,WSH,0,0,0,...,150406_161010,2486.0,5,0,0,Strategic,Standard,1,2_2,fb:0_sb:0_tb:0
16292,CH,2015-04-06,434158,87.2,14.0,L,WSH,0,0,0,...,150406_160954,1765.0,4,0,0,Strategic,Standard,1,1_2,fb:0_sb:0_tb:0
16293,FF,2015-04-06,434158,95.6,11.0,L,WSH,0,0,0,...,150406_160940,2639.0,3,0,0,Strategic,Standard,1,0_2,fb:0_sb:0_tb:0
16294,FF,2015-04-06,434158,94.2,11.0,L,WSH,0,0,0,...,150406_160925,2613.0,2,0,0,Strategic,Standard,1,0_1,fb:0_sb:0_tb:0
16295,FF,2015-04-06,434158,91.2,13.0,L,WSH,0,0,0,...,150406_160913,2338.0,1,0,0,Strategic,Standard,1,0_0,fb:0_sb:0_tb:0

## Feature Engineering

In [10]:
madmax = madmax[['pitch_type', 'game_date', 'sv_id', 'batter', 'pitch_number', 'release_speed', 'zone', 
                 'stand', 'home_team', 'on_3b', 'on_2b', 'on_1b', 'outs_when_up', 'inning', 
                 'release_spin_rate', 'opp_score', 'nats_score','if_fielding_alignment', 
                 'of_fielding_alignment', 'nats_home1_away0', 'balls_strikes', 'all_runners']]

In [11]:
madmax = madmax.sort_values(by='sv_id')

In [12]:
madmax['pitch'] = 1

In [15]:
madmax['pitch_season'] = madmax.pitch.cumsum() - 1
madmax['pitch_game'] = madmax.groupby(['game_date'])['pitch'].cumsum() - 1
madmax['pitch_bat_gm'] = madmax.groupby(['game_date', 'batter'])['pitch'].cumsum() - 1
madmax.pitch_number = madmax.pitch_number - 1
# madmax[['pitch_type', 'game_date','batter', 'pitch_number', 'pitch_bat_gm']].loc[madmax.batter == 607043]

In [16]:
madmax = madmax.drop(columns = ['pitch'])
madmax[['pitch_type', 'game_date', 'sv_id', 'batter', 
        'pitch_number', 'pitch_bat_gm', 'pitch_game', 'pitch_season', 
        'release_speed', 'zone', 'stand', 'home_team', 
        'on_3b', 'on_2b', 'on_1b', 'outs_when_up', 'inning', 
        'release_spin_rate', 'opp_score', 'nats_score', 'if_fielding_alignment', 'of_fielding_alignment',
        'nats_home1_away0', 'balls_strikes', 'all_runners']]

,pitch_type,game_date,sv_id,batter,pitch_number,pitch_bat_gm,pitch_game,pitch_season,release_speed,zone,...,outs_when_up,inning,release_spin_rate,opp_score,nats_score,if_fielding_alignment,of_fielding_alignment,nats_home1_away0,balls_strikes,all_runners
16295,FF,2015-04-06,150406_160913,434158,-2,0,0,0,91.2,13.0,...,0,1,2338.0,0,0,Strategic,Standard,1,0_0,fb:0_sb:0_tb:0
16294,FF,2015-04-06,150406_160925,434158,-1,1,1,1,94.2,11.0,...,0,1,2613.0,0,0,Strategic,Standard,1,0_1,fb:0_sb:0_tb:0
16293,FF,2015-04-06,150406_160940,434158,0,2,2,2,95.6,11.0,...,0,1,2639.0,0,0,Strategic,Standard,1,0_2,fb:0_sb:0_tb:0
16292,CH,2015-04-06,150406_160954,434158,1,3,3,3,87.2,14.0,...,0,1,1765.0,0,0,Strategic,Standard,1,1_2,fb:0_sb:0_tb:0
16291,FF,2015-04-06,150406_161010,434158,2,4,4,4,94.7,11.0,...,0,1,2486.0,0,0,Strategic,Standard,1,2_2,fb:0_sb:0_tb:0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13810,NaN,2015-08-20,NaN,471865,1,8,99,16291,38.4,11.0,...,1,5,967.0,1,0,Strategic,Standard,0,3_0,fb:0_sb:1_tb:1
13811,NaN,2015-08-20,NaN,471865,0,9,100,16292,38.8,11.0,...,1,5,993.0,1,0,Strategic,Standard,0,2_0,fb:0_sb:1_tb:1
13812,NaN,2015-08-20,NaN,471865,-1,10,101,16293,37.9,11.0,...,1,5,956.0,1,0,Strategic,Standard,0,1_0,fb:0_sb:1_tb:1
13813,NaN,2015-08-20,NaN,471865,-2,11,102,16294,41.5,11.0,...,1,5,1048.0,1,0,Strategic,Standard,0,0_0,fb:0_sb:1_tb:1
13947,NaN,2015-08-09,NaN,518614,1,9,83,16295,NaN,NaN,...,2,6,NaN,3,3,NaN,NaN,1,3_0,fb:0_sb:1_tb:0