In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import pickle
%matplotlib inline

In [2]:
filepath = '../data/savant/'

infile = open(filepath + 'all_pitcher_data_2019.pickle','rb')
pitchers = pickle.load(infile)
infile.close()

In [3]:
pitchers.head();

In [4]:
pitchers.columns

Index(['pitch_type', 'game_date', 'release_speed', 'release_pos_x',
       'release_pos_z', 'player_name', 'batter', 'pitcher', 'events',
       'description', 'spin_dir', 'spin_rate_deprecated',
       'break_angle_deprecated', 'break_length_deprecated', 'zone', 'des',
       'game_type', 'stand', 'p_throws', 'home_team', 'away_team', 'type',
       'hit_location', 'bb_type', 'balls', 'strikes', 'game_year', 'pfx_x',
       'pfx_z', 'plate_x', 'plate_z', 'on_3b', 'on_2b', 'on_1b',
       'outs_when_up', 'inning', 'inning_topbot', 'hc_x', 'hc_y',
       'tfs_deprecated', 'tfs_zulu_deprecated', 'fielder_2', 'umpire', 'sv_id',
       'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'sz_top', 'sz_bot',
       'hit_distance_sc', 'launch_speed', 'launch_angle', 'effective_speed',
       'release_spin_rate', 'release_extension', 'game_pk', 'pitcher.1',
       'fielder_2.1', 'fielder_3', 'fielder_4', 'fielder_5', 'fielder_6',
       'fielder_7', 'fielder_8', 'fielder_9', 'release_pos_y',
       'estimated_ba_using_speedangle', 'estimated_woba_using_speedangle',
       'woba_value', 'woba_denom', 'babip_value', 'iso_value',
       'launch_speed_angle', 'at_bat_number', 'pitch_number', 'pitch_name',
       'home_score', 'away_score', 'bat_score', 'fld_score', 'post_away_score',
       'post_home_score', 'post_bat_score', 'post_fld_score',
       'if_fielding_alignment', 'of_fielding_alignment'],
      dtype='object')

In [5]:
keep_cols = ['pitch_type', 'sv_id', 'game_date', 'player_name', 'batter', 'pitcher','stand', 'p_throws', 
             'balls', 'strikes', 'game_year', 'on_3b', 'on_2b', 'on_1b', 'outs_when_up', 'inning', 
             'inning_topbot', 'pitch_number', 'home_score', 'away_score']

kill_cols = []

for k in pitchers.columns:
    if k in keep_cols:
        pass
    else:
        kill_cols.append(k)

In [6]:
pitchers = pitchers.drop(columns = kill_cols)

In [7]:
pitchers

,pitch_type,game_date,player_name,batter,pitcher,stand,p_throws,balls,strikes,game_year,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,sv_id,pitch_number,home_score,away_score
0,FF,2019-09-22,Trevor Bauer,643446,545333,L,R,1,1,2019,642708.0,NaN,NaN,2,7,Top,190922_192239,3,2,5
1,FC,2019-09-22,Trevor Bauer,643446,545333,L,R,1,0,2019,642708.0,NaN,NaN,2,7,Top,190922_192204,2,2,5
2,FC,2019-09-22,Trevor Bauer,643446,545333,L,R,0,0,2019,642708.0,NaN,NaN,2,7,Top,190922_192140,1,2,5
3,KC,2019-09-22,Trevor Bauer,607043,545333,L,R,0,2,2019,NaN,642708.0,NaN,1,7,Top,190922_192046,3,2,5
4,FF,2019-09-22,Trevor Bauer,607043,545333,L,R,0,1,2019,NaN,642708.0,NaN,1,7,Top,190922_192008,2,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,FF,2019-03-28,Nick Vincent,614173,543883,L,R,0,2,2019,NaN,NaN,595978.0,0,8,Bot,190328_221821,3,2,0
747,FC,2019-03-28,Nick Vincent,614173,543883,L,R,0,1,2019,NaN,NaN,595978.0,0,8,Bot,190328_221753,2,2,0
748,FC,2019-03-28,Nick Vincent,614173,543883,L,R,0,0,2019,NaN,NaN,595978.0,0,8,Bot,190328_221732,1,2,0
749,FT,2019-03-28,Nick Vincent,595978,543883,R,R,0,1,2019,NaN,NaN,NaN,0,8,Bot,190328_221657,2,2,0
750,FC,2019-03-28,Nick Vincent,595978,543883,R,R,0,0,2019,NaN,NaN,NaN,0,8,Bot,190328_221636,1,2,0

## Fill nulls

In [8]:
pitchers.isnull().sum()

pitch_type         2573
game_date             0
player_name           0
batter                0
pitcher               0
stand                 0
p_throws              0
balls                 0
strikes               0
game_year             0
on_3b            546179
on_2b            493091
on_1b            422099
outs_when_up          0
inning                0
inning_topbot         0
sv_id              2172
pitch_number          0
home_score            0
away_score            0
dtype: int64

In [9]:
pitchers = pitchers.dropna(subset=['pitch_type'])
pitchers = pitchers.dropna(subset=['sv_id'])

In [10]:
pitchers.on_3b = pitchers.on_3b.fillna(value=0)
pitchers.on_2b = pitchers.on_2b.fillna(value=0)
pitchers.on_1b = pitchers.on_1b.fillna(value=0)

In [11]:
pitchers.isnull().sum()

pitch_type       0
game_date        0
player_name      0
batter           0
pitcher          0
stand            0
p_throws         0
balls            0
strikes          0
game_year        0
on_3b            0
on_2b            0
on_1b            0
outs_when_up     0
inning           0
inning_topbot    0
sv_id            0
pitch_number     0
home_score       0
away_score       0
dtype: int64

In [12]:
pitchers

,pitch_type,game_date,player_name,batter,pitcher,stand,p_throws,balls,strikes,game_year,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,sv_id,pitch_number,home_score,away_score
0,FF,2019-09-22,Trevor Bauer,643446,545333,L,R,1,1,2019,642708.0,0.0,0.0,2,7,Top,190922_192239,3,2,5
1,FC,2019-09-22,Trevor Bauer,643446,545333,L,R,1,0,2019,642708.0,0.0,0.0,2,7,Top,190922_192204,2,2,5
2,FC,2019-09-22,Trevor Bauer,643446,545333,L,R,0,0,2019,642708.0,0.0,0.0,2,7,Top,190922_192140,1,2,5
3,KC,2019-09-22,Trevor Bauer,607043,545333,L,R,0,2,2019,0.0,642708.0,0.0,1,7,Top,190922_192046,3,2,5
4,FF,2019-09-22,Trevor Bauer,607043,545333,L,R,0,1,2019,0.0,642708.0,0.0,1,7,Top,190922_192008,2,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,FF,2019-03-28,Nick Vincent,614173,543883,L,R,0,2,2019,0.0,0.0,595978.0,0,8,Bot,190328_221821,3,2,0
747,FC,2019-03-28,Nick Vincent,614173,543883,L,R,0,1,2019,0.0,0.0,595978.0,0,8,Bot,190328_221753,2,2,0
748,FC,2019-03-28,Nick Vincent,614173,543883,L,R,0,0,2019,0.0,0.0,595978.0,0,8,Bot,190328_221732,1,2,0
749,FT,2019-03-28,Nick Vincent,595978,543883,R,R,0,1,2019,0.0,0.0,0.0,0,8,Bot,190328_221657,2,2,0
750,FC,2019-03-28,Nick Vincent,595978,543883,R,R,0,0,2019,0.0,0.0,0.0,0,8,Bot,190328_221636,1,2,0

In [13]:
pitchers.game_date = pd.to_datetime(pitchers.game_date)

In [14]:
pitchers['stand_0right'] = pitchers.stand.apply(lambda c: 0 if c == 'R' else '1')
pitchers = pitchers.drop(columns = 'stand')

pitchers.on_3b = pitchers.on_3b.apply(lambda c: 0 if c == 0 else 1)
pitchers.on_2b = pitchers.on_2b.apply(lambda c: 0 if c == 0 else 1)
pitchers.on_1b = pitchers.on_1b.apply(lambda c: 0 if c == 0 else 1)

pitchers['pitcher_home0'] = pitchers.inning_topbot.apply(lambda c: 0 if c == 'Top' else 1)
pitchers = pitchers.drop(columns = 'inning_topbot')

pitchers['p_throws_0right'] = pitchers.p_throws.apply(lambda c: 0 if c == 'R' else 1)
pitchers = pitchers.drop(columns = 'p_throws')

In [15]:
pitchers

,pitch_type,game_date,player_name,batter,pitcher,balls,strikes,game_year,on_3b,on_2b,on_1b,outs_when_up,inning,sv_id,pitch_number,home_score,away_score,stand_0right,pitcher_home0,p_throws_0right
0,FF,2019-09-22,Trevor Bauer,643446,545333,1,1,2019,1,0,0,2,7,190922_192239,3,2,5,1,0,0
1,FC,2019-09-22,Trevor Bauer,643446,545333,1,0,2019,1,0,0,2,7,190922_192204,2,2,5,1,0,0
2,FC,2019-09-22,Trevor Bauer,643446,545333,0,0,2019,1,0,0,2,7,190922_192140,1,2,5,1,0,0
3,KC,2019-09-22,Trevor Bauer,607043,545333,0,2,2019,0,1,0,1,7,190922_192046,3,2,5,1,0,0
4,FF,2019-09-22,Trevor Bauer,607043,545333,0,1,2019,0,1,0,1,7,190922_192008,2,2,5,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,FF,2019-03-28,Nick Vincent,614173,543883,0,2,2019,0,0,1,0,8,190328_221821,3,2,0,1,1,0
747,FC,2019-03-28,Nick Vincent,614173,543883,0,1,2019,0,0,1,0,8,190328_221753,2,2,0,1,1,0
748,FC,2019-03-28,Nick Vincent,614173,543883,0,0,2019,0,0,1,0,8,190328_221732,1,2,0,1,1,0
749,FT,2019-03-28,Nick Vincent,595978,543883,0,1,2019,0,0,0,0,8,190328_221657,2,2,0,0,1,0
750,FC,2019-03-28,Nick Vincent,595978,543883,0,0,2019,0,0,0,0,8,190328_221636,1,2,0,0,1,0

## Feature Engineering

In [16]:
# Sort table cronologically by pitcher
pitchers = pitchers.sort_values(by = ['sv_id'])

### Create running total of pitches thrown in the season per pitcher

In [17]:
pitchers['pitch'] = 1

In [18]:
pitchers['pitch_season'] = pitchers.groupby(['player_name'])['pitch'].cumsum() - 1

### Total pitches per game

In [19]:
pitchers['pitch_game'] = pitchers.groupby(['player_name', 'game_date'])['pitch'].cumsum() - 1

### Create running total of pitches thrown to each batter per game

In [20]:
pitchers['pitch_bat_gm'] = pitchers.groupby(['player_name', 'game_date', 'batter'])['pitch'].cumsum() - 1

### Pitches per current at bat

In [21]:
pitchers['pitch_ab'] = pitchers.pitch_number - 1
pitchers = pitchers.drop(columns = ['pitch_number', 'pitch', 'sv_id'])

In [22]:
pitchers.loc[pitchers.player_name == 'Justin Verlander']

,pitch_type,game_date,player_name,batter,pitcher,balls,strikes,game_year,on_3b,on_2b,...,inning,home_score,away_score,stand_0right,pitcher_home0,p_throws_0right,pitch_season,pitch_game,pitch_bat_gm,pitch_ab
3447,FF,2019-03-28,Justin Verlander,640457,434378,0,0,2019,0,0,...,1,0,0,1,1,0,0,0,0,0
3446,FF,2019-03-28,Justin Verlander,640457,434378,1,0,2019,0,0,...,1,0,0,1,1,0,1,1,1,1
3445,SL,2019-03-28,Justin Verlander,640457,434378,1,1,2019,0,0,...,1,0,0,1,1,0,2,2,2,2
3444,FF,2019-03-28,Justin Verlander,640457,434378,2,1,2019,0,0,...,1,0,0,1,1,0,3,3,3,3
3443,FF,2019-03-28,Justin Verlander,502054,434378,0,0,2019,0,0,...,1,1,0,0,1,0,4,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,FF,2019-09-28,Justin Verlander,594777,434378,0,1,2019,0,0,...,6,3,5,1,1,0,3284,75,7,1
3,CU,2019-09-28,Justin Verlander,594777,434378,0,2,2019,0,0,...,6,3,5,1,1,0,3285,76,8,2
2,FF,2019-09-28,Justin Verlander,594777,434378,1,2,2019,0,0,...,6,3,5,1,1,0,3286,77,9,3
1,FF,2019-09-28,Justin Verlander,592743,434378,0,0,2019,0,0,...,6,3,5,0,1,0,3287,78,4,0
0,SL,2019-09-28,Justin Verlander,592743,434378,0,1,2019,0,0,...,6,3,5,0,1,0,3288,79,5,1

In [23]:
# Reorder columns
pitchers = pitchers[['pitch_type', 'game_date', 'game_year', 'player_name', 'batter', 'pitcher', 
                     'balls', 'strikes', 'outs_when_up', 'on_3b', 'on_2b', 'on_1b', 'inning', 
                     'home_score', 'away_score', 'stand_0right', 'pitcher_home0', 'p_throws_0right', 
                     'pitch_season', 'pitch_game', 'pitch_bat_gm', 'pitch_ab']]

In [24]:
filepath = '../data/processed/pitchers/'

outfile = open(filepath + 'cleaned.pickle','wb')
pitchers = pickle.dump(pitchers, outfile)
outfile.close()