In [16]:
import pandas as pd
import numpy as np
import pickle

In [17]:
batters_og = pd.read_csv('../data/processed/2019_to_2015_batter_data_by_ab.csv', index_col=0)

In [18]:
batters_og.head()

,pitches,player_id,player_name,game_date,total_pitches,pitch_percent,ba,iso,babip,slg,...,eff_min_vel,release_extension,pos3_int_start_distance,pos4_int_start_distance,pos5_int_start_distance,pos6_int_start_distance,pos7_int_start_distance,pos8_int_start_distance,pos9_int_start_distance,team
0,5,405395,Albert Pujols,2019-04-13,5,100.0,NaN,NaN,NaN,NaN,...,-1.1,5.68,112.0,166.0,124.0,169.0,300.0,326.0,289.0,laa2019
1,5,621493,Taylor Ward,2019-07-23,5,100.0,NaN,NaN,NaN,NaN,...,-1.1,5.45,116.0,157.0,108.0,143.0,292.0,313.0,281.0,laa2019
2,5,571718,Brian Goodwin,2019-08-24,5,100.0,NaN,NaN,NaN,NaN,...,-0.4,6.20,121.0,150.0,104.0,153.0,278.0,315.0,311.0,laa2019
3,8,405395,Albert Pujols,2019-05-20,8,100.0,NaN,NaN,NaN,NaN,...,-1.4,5.48,86.0,146.0,120.0,143.0,313.0,331.0,294.0,laa2019
4,5,660271,Shohei Ohtani,2019-07-24,5,100.0,NaN,NaN,NaN,NaN,...,0.1,6.15,129.0,183.0,126.0,152.0,302.0,324.0,312.0,laa2019

In [19]:
batters_og.columns

Index(['pitches', 'player_id', 'player_name', 'game_date', 'total_pitches',
       'pitch_percent', 'ba', 'iso', 'babip', 'slg', 'woba', 'xwoba', 'xba',
       'hits', 'abs', 'launch_speed', 'launch_angle', 'spin_rate', 'velocity',
       'effective_speed', 'whiffs', 'swings', 'takes', 'eff_min_vel',
       'release_extension', 'pos3_int_start_distance',
       'pos4_int_start_distance', 'pos5_int_start_distance',
       'pos6_int_start_distance', 'pos7_int_start_distance',
       'pos8_int_start_distance', 'pos9_int_start_distance', 'team'],
      dtype='object')

In [12]:
keep_cols = ['game_date', 'player_name', 'batter', 'events', 'description', 'des',
            'bb_type', 'sv_id', 'woba_value', 'woba_denom', 'babip_value', 'iso_value']

kill_cols = []
for c in batters_og.columns:
    if c in keep_cols:
        pass
    else:
        kill_cols.append(c)

In [13]:
batters = batters_og.drop(columns = kill_cols)
batters.head()

     player_name   game_date
0  Albert Pujols  2019-04-13
1    Taylor Ward  2019-07-23
2  Brian Goodwin  2019-08-24
3  Albert Pujols  2019-05-20
4  Shohei Ohtani  2019-07-24

## Capture at bat events by type
Types include:
- At bat
- Single
- Double
- Triple
- Home run
- Strike outs
- Walks

In [14]:
batters.events.unique()

AttributeError: 'DataFrame' object has no attribute 'events'

In [15]:
# Capture at bats
batters['ab'] = batters['events'].apply(lambda e: 0 if e == 'walk' or \
                                        e == 'hit_by_pitch' or \
                                        e == 'sac_fly' or \
                                        e == 'sac_bunt' or \
                                        e == 'catcher_interf' or \
                                        e == 'sac_fly_double_play' or \
                                        e == 'sac_bunt_double_play'
                                        else 1)

KeyError: 'events'

In [9]:
# Capture strikeouts
batters['k'] = batters['events'].apply(lambda e: 1 if e == 'strikeout' or e == 'strikeout_double_play' else 0)

In [10]:
# Capture walks
batters['walk'] = batters['events'].apply(lambda e: 1 if e == 'walk' else 0)

In [11]:
# Capture singles
batters['single'] = batters['events'].apply(lambda e: 1 if e == 'single' else 0)

In [12]:
# Capture doubles
batters['double'] = batters['events'].apply(lambda e: 1 if e == 'double' else 0)

In [13]:
# Capture triples
batters['triple'] = batters['events'].apply(lambda e: 1 if e == 'triple' else 0)

In [14]:
# Capture home runs
batters['hr'] = batters['events'].apply(lambda e: 1 if e == 'home_run' else 0)

In [15]:
# Capture sacrifices
batters['sac'] = batters['events'].apply(lambda e: 1 if e == 'sac_fly' or \
                                         e == 'sac_bunt' or \
                                         e == 'sac_fly_double_play' or \
                                         e == 'sac_bunt_double_play'\
                                         else 0)

## Type of contact per each hitter
Types include:
- Line drive
- Ground_ball
- Fly ball
- Popup

In [16]:
batters.loc[batters.bb_type.isnull()];

In [17]:
# Capture line_drives
batters['line_drive'] = batters['bb_type'].apply(lambda e: 1 if e == 'line_drive' else 0)

In [18]:
# Capture ground balls
batters['ground_ball'] = batters['bb_type'].apply(lambda e: 1 if e == 'ground_ball' else 0)

In [19]:
# Capture line_drives
batters['fly_ball'] = batters['bb_type'].apply(lambda e: 1 if e == 'fly_ball' else 0)

In [20]:
# Capture line_drives
batters['popup'] = batters['bb_type'].apply(lambda e: 1 if e == 'popup' else 0)

In [21]:
batters;

## Generate RBIs

In [22]:
batters['rbi'] = batters['des'].apply(lambda r: r.count('scores'))

## Clean up data frame

In [23]:
batters.columns

Index(['game_date', 'player_name', 'batter', 'events', 'description', 'des',
       'bb_type', 'sv_id', 'woba_value', 'woba_denom', 'babip_value',
       'iso_value', 'ab', 'k', 'walk', 'single', 'double', 'triple', 'hr',
       'sac', 'line_drive', 'ground_ball', 'fly_ball', 'popup', 'rbi'],
      dtype='object')

In [24]:
kill_cols_v2 = ['events', 'description', 'des', 'bb_type', 'woba_value', 'woba_denom', 'babip_value', 'iso_value']

In [25]:
batters = batters.drop(columns = kill_cols_v2)

In [26]:
outfile = open('../data/processed/batter_ab_cleaned.pickle','wb')
pickle.dump(batters, outfile)
outfile.close()

In [27]:
batters.game_date = pd.to_datetime(batters.game_date)
batters.sort_values(by=['batter', 'game_date'])

,game_date,player_name,batter,sv_id,ab,k,walk,single,double,triple,hr,sac,line_drive,ground_ball,fly_ball,popup,rbi
5119,2019-04-30,CC Sabathia,282332,190501_025719,1,1,0,0,0,0,0,0,0,0,0,0,0
5128,2019-04-30,CC Sabathia,282332,190501_022236,1,1,0,0,0,0,0,0,0,0,0,0,0
1222,2019-08-24,CC Sabathia,282332,190824_204936,1,0,0,0,0,0,0,0,1,0,0,0,0
6193,2019-03-20,Ichiro Suzuki,400085,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0
6202,2019-03-20,Ichiro Suzuki,400085,NaN,1,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4559,2019-05-12,Nick Margevicius,676606,190512_195709,1,0,0,1,0,0,0,0,1,0,0,0,0
4386,2019-05-18,Nick Margevicius,676606,190519_013713,1,1,0,0,0,0,0,0,0,0,0,0,0
3943,2019-06-01,Nick Margevicius,676606,190602_024752,1,0,0,0,0,0,0,0,0,1,0,0,0
3723,2019-06-07,Nick Margevicius,676606,190608_024737,1,0,0,0,0,0,0,0,0,1,0,0,0
3402,2019-06-16,Nick Margevicius,676606,190616_200907,1,1,0,0,0,0,0,0,0,0,0,0,0

In [28]:
numeric_cols = ['ab', 'k', 'walk', 'single', 'double', 'triple', 'hr', 'sac', 
                'line_drive', 'ground_ball', 'fly_ball', 'popup', 'rbi']

In [29]:
batters_game = batters.groupby(by = ['batter', 'game_date', 'player_name'], axis = 0).sum()

In [30]:
batters_game.loc[batters_game.index.get_level_values(2) == 'Bryce Harper']

                                ab  k  walk  single  double  triple  hr  sac  \
batter game_date  player_name
547180 2019-03-28 Bryce Harper   3  2     0       0       0       0   0    0
       2019-03-30 Bryce Harper   3  0     1       0       0       0   1    0
       2019-03-31 Bryce Harper   3  1     2       0       1       0   1    0
       2019-04-02 Bryce Harper   5  2     0       1       1       0   1    0
       2019-04-03 Bryce Harper   2  0     1       2       0       0   0    0
...                             .. ..   ...     ...     ...     ...  ..  ...
       2019-09-25 Bryce Harper   4  1     0       1       1       0   0    0
       2019-09-26 Bryce Harper   4  3     0       0       0       0   0    0
       2019-09-27 Bryce Harper   6  1     0       0       1       1   0    1
       2019-09-28 Bryce Harper   4  0     0       0       0       0   1    0
       2019-09-29 Bryce Harper   5  1     0       2       0       0   0    0

                                line_drive  ground_ball  fly_ball  popup  rbi
batter game_date  player_name
547180 2019-03-28 Bryce Harper           0            1         0      0    0
       2019-03-30 Bryce Harper           0            0         3      0    0
       2019-03-31 Bryce Harper           1            0         1      0    0
       2019-04-02 Bryce Harper           1            1         1      0    2
       2019-04-03 Bryce Harper           1            1         0      0    0
...                                    ...          ...       ...    ...  ...
       2019-09-25 Bryce Harper           1            1         1      0    0
       2019-09-26 Bryce Harper           0            1         0      0    0
       2019-09-27 Bryce Harper           2            2         2      0    2
       2019-09-28 Bryce Harper           0            0         2      2    2
       2019-09-29 Bryce Harper           3            0         1      0    0

[155 rows x 13 columns]

In [31]:
batters_game.to_csv('../data/processed/batters_by_game_grouped.csv')

In [32]:
outfile = open('../data/processed/batter_ab_cleaned_grouped.pickle','wb')
pickle.dump(batters_game ,outfile)
outfile.close()

outfile = open('../data/processed/batter_ab_cleaned.pickle','wb')
pickle.dump(batters_game ,outfile)
outfile.close()